//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE_Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FE_Randomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xCC5B50 0xCC5B60
        ///0xCC5BD0 0xCC5BF0 0xCC5C00 0xCC5C10 0xCC5C20
        ///0xCC5D28 0xCC5D38 0xCC5D48 0xCC5D58 0xCC5D68 0xCC5D88
        ///0xCC5EC8 0xCC5ED8 0xCC5EE8 0xCC5F08 0xCC5F18 0xCC5F28 0xCC5F38 0xCC5F48 0xCC5F58
        ///0xCC6098 0xCC60A8 0xCC60C8 0xCC60D8 0xCC60E8 0xCC60F8 0xCC6108 0xCC6118 0xCC6128 0xCC6138 0xCC6148 0xCC6158 0xCC6168 0xCC61A8 0xCC61B8 0xCC61D8 0xCC61F8
        ///0xCC6320 0xCC6330 0xCC6340 0xCC6360 0xCC6370 0xCC6390 0xCC63A0
        ///0xCC6620 0xCC6630 0xCC6640 0xCC6650 0xCC6660 0xCC6670 0xCC6680 0xCC6690 0xCC66A0 0xCC66B0 0x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string allFE7Units {
            get {
                return ResourceManager.GetString("allFE7Units", resourceCulture);
            }
        }
    }
}
